# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CitiFleet' do
pod 'Alamofire', '~> 3.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'GoogleMaps', '~> 1.12'
pod 'SwiftValidator', '~> 3.0'
pod 'SwiftyJSON', '~> 2.3'
pod 'ReachabilitySwift', '~> 2.3'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

pod 'Fabric'
pod 'Crashlytics'
end