# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CitiFleet' do
pod 'Alamofire', '~> 3.2'
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'GoogleMaps', '~> 1.12'
pod 'SwiftValidator', '~> 3.0'
pod 'SwiftyJSON', '~> 2.3'
pod 'ReachabilitySwift', '~> 2.3'
pod 'HanekeSwift', '~> 0.10'
pod 'RSBarcodes_Swift', '~> 0.1'
pod 'Cosmos', '~> 1.2'
pod 'NYTPhotoViewer', '~> 1.1.0'
pod 'Kingfisher', '~> 2.1'
pod 'KMPlaceholderTextView', '~> 1.1.2' 

pod 'FBSDKCoreKit', '~> 4.10'
pod 'FBSDKLoginKit', '~> 4.10'

pod 'TwitterKit', '~> 1.15'
pod 'TwitterCore', '~> 1.15'

pod 'SwiftAddressBook', '~> 0.6'

pod 'Fabric'
pod 'Crashlytics'
end